#server:
#  port: 8083
server:
  port: 8088
spring:
  profiles:
    active: test
---
server:
  port: 8089
spring:
  profiles:
    active: dev
---
server:
  port: 8090
spring:
  profiles:
    active: test
debug: true