server:
  port: 8091


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-demo1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: hhnwdzsv

Logging:
  level:
    com.sunyx: debug
